Added missing require absence of
vitruv-tools/Vitruv-CaseStudies pull request #270
Opened 2023-05-25 17:07 UTC by Temeraire130

2023-05-25 17:12 UTC, TomWerm approved these changes

2023-06-06 14:53 UTC, tsaglam commented
@Temeraire130 I think your latest commit accidentally included more than the required changes.

2023-06-06 14:55 UTC, TomWerm requested changes
Remove generated files please

2023-06-07 06:44 UTC, TomWerm approved these changes

2023-06-07 06:59 UTC, merged